image: node:12.13.0-alpine
before_script:
  - npm install -g firebase-tools
  - npm install
unit-tests:
  stage: test
  script:
    - npm run-script test
build:
  stage: build
  script:
    - npm run-script build
production:
  stage: deploy
  script:
    - npm run-script deploy
  only:
    - master
  environment:
    name: production
    url: https://mokuroku-e0b82.web.app/
